### ISSUE TITLE
O modal de seleção de modelo de relatório não fecha quando sem a API Key

### ISSUE THREAD

**Issue by matheuscruzsouza** [doctor-assistant/daai-component#10]
Quando aberto o modal de seleção de modelo de relatório, quando sem a API key, o mesmo não retorna nenhum dado e não fecha, impedindo a utilização do sistema abaixo do backdrop, podendo gerar atrito com clientes por necessitar atualizar a página para poder voltar a utilizar a aplicação.

**Comment by vitoriacst** [comment]
**Versão 1.0.3**

Issues solucionada na versão 1.0.3 do daai-component.

**Comment by rdemorais** [comment]
@matheuscruzsouza depois de testar a versão 1.0.3, nos avise para fecharmos essa issue. Obrigado.

**Comment by matheuscruzsouza** [comment]
O problema já está corrigido. Obrigado.
