### ISSUE TITLE
Criar um signal emitter no componente para que possa ser atualizada as interfaces onde o mesmo for aplicado.

### ISSUE THREAD

**Issue by matheuscruzsouza** [doctor-assistant/daai-component#19]
Criar um signal emitter que funcione com o addEventistener do javascript e passe o estado e ações executadas no componente para que possa ser alterada a interface que dependa do estado atual do componente.

Exemplo:
- Ao clicar no botão para iniciar a gravação, emitir um evento de "RECORD START".
- Ao pausar a gravação, emitir o evento "RECORD PAUSE".
- Ao clicar para parar a gravação, emitir o evento de "RECORD END".
Assim por diante...

Isso facilitaria a integração com os prontuários, permitindo que eles utilizem os eventos do componente na interface.

**Comment by vitoriacst** [comment]
resolvido na versão 1.2.1
