### ISSUE TITLE
Quando a requisição é executada com erro, o mesmo retorna como um sucesso

### ISSUE THREAD

**Issue by matheuscruzsouza** [doctor-assistant/daai-component#20]
![REQUEST](https://github.com/user-attachments/assets/891904de-8037-4ced-8acb-1f7b44ca2df6)
![RESPONSE](https://github.com/user-attachments/assets/c44577db-315e-47ae-9ed4-7923b7b5033d)

_Originally posted by @matheuscruzsouza in https://github.com/doctor-assistant/daai-component/issues/17#issuecomment-2442022376_

**Comment by vitoriacst** [comment]
Resolvida na versão 1.2.2

**Comment by vitoriacst** [comment]
Resolvida na versão 1.2.2
