### ISSUE TITLE
[CDN][BADGE] Event listener não funciona por causa de erro

### ISSUE THREAD

**Issue by matheuscruzsouza** [doctor-assistant/daai-component#34]
Ao iniciar a requisição do SSE, é feito o log de erro a seguir:

```
index.esm.js:1872 Uncaught (in promise) TypeError: Failed to execute 'dispatchEvent' on 'EventTarget': parameter 1 is not of type 'Event'.
    at Oa.reconnect (index.esm.js:1872:10)
    at Oa.connect (index.esm.js:1863:18)
```

As requisições ocorrem com o backend da DAAI, mas não são repassadas ao meu frontend, impedindo a implementação das funcionalidades.

**Comment by vitoriacst** [comment]
Resolvido!
problema causado pela versão do angular js
